default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: react_rails_helloworld_development

test:
  <<: *default
  database: react_rails_helloworld_test

production:
  <<: *default
  url: <%= ENV["MY_APP_DATABASE_URL"] %>
  database: react_rails_helloworld_production
  username: react_rails_helloworld
  password: <%= ENV["REACT_RAILS_HELLOWORLD_DATABASE_PASSWORD"] %>
